# Training Configuration for Cutlery Classifier MVP

# Data Configuration
data:
  raw_data_path: "data/raw"
  processed_data_path: "data/processed"
  augmented_data_path: "data/augmented"
  image_size: [320, 320]
  batch_size: 32
  num_workers: 4
  train_split: 0.7
  val_split: 0.2
  test_split: 0.1

# Model Configuration
model:
  architecture: "resnet18" # Options: resnet18, mobilenet_v2
  pretrained: true
  num_classes: 9 # 3 manufacturers x 3 cutlery types
  dropout_rate: 0.5
  freeze_backbone: false # Set to true for feature extraction only

# Training Configuration
training:
  epochs: 10
  learning_rate: 0.001
  weight_decay: 0.0001
  optimizer: "adam" # Options: adam, sgd
  scheduler: "step" # Options: step, cosine, plateau
  step_size: 5
  gamma: 0.1
  early_stopping_patience: 5
  save_best_only: true

# Data Augmentation
augmentation:
  horizontal_flip: 0.5
  rotation_degrees: 15
  color_jitter:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.1
  gaussian_blur: 0.1
  normalize:
    mean: [0.485, 0.456, 0.406] # ImageNet standards
    std: [0.229, 0.224, 0.225]

# Paths
paths:
  model_save_dir: "models/checkpoints"
  export_dir: "models/exports"
  results_dir: "results"
  logs_dir: "logs"

# Class Names (update based on your manufacturers)
classes:
  - "manufacturer_a_knife"
  - "manufacturer_a_fork"
  - "manufacturer_a_spoon"
  - "manufacturer_b_knife"
  - "manufacturer_b_fork"
  - "manufacturer_b_spoon"
  - "manufacturer_c_knife"
  - "manufacturer_c_fork"
  - "manufacturer_c_spoon"

# Evaluation
evaluation:
  metrics: ["accuracy", "precision", "recall", "f1"]
  confusion_matrix: true
  grad_cam: true
  top_k: 3

# Export Settings
export:
  formats: ["pt", "onnx"]
  optimize_for_mobile: false
  quantization: false

# Logging
logging:
  level: "INFO"
  tensorboard: true
  save_plots: true
  plot_format: "png"

# Hardware
device: "auto" # Options: auto, cpu, cuda
mixed_precision: false
