# Training Configuration for Cutlery Classifier MVP (Augmented Dataset)

# Data Configuration
data:
  raw_data_path: "data/raw"
  processed_data_path: "data/augmented" # Changed to use augmented data for training
  augmented_data_path: "data/augmented"
  image_size: [320, 320]
  batch_size: 32
  num_workers: 4
  train_split: 0.7
  val_split: 0.2
  test_split: 0.1
  grayscale: true # Using grayscale for efficiency

# Model Configuration
model:
  architecture: "resnet18" # Options: resnet18, mobilenet_v2
  pretrained: true
  num_classes: 3 # Type detection: fork, knife, spoon
  dropout_rate: 0.5
  freeze_backbone: false # Set to true for feature extraction only
  input_channels: 1 # Grayscale input

# Training Configuration
training:
  epochs: 30
  learning_rate: 0.001
  weight_decay: 0.0001
  optimizer: "adam" # Options: adam, sgd
  scheduler: "step" # Options: step, cosine, plateau
  step_size: 10
  gamma: 0.1
  early_stopping_patience: 8
  save_best_only: true

# Data Augmentation
augmentation:
  horizontal_flip: 0.5
  rotation_degrees: 15
  color_jitter:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.0 # Disabled for grayscale
    hue: 0.0 # Disabled for grayscale
  gaussian_blur: 0.1
  normalize:
    mean: [0.449] # Grayscale ImageNet equivalent
    std: [0.226]

# Paths
paths:
  model_save_dir: "models/checkpoints"
  export_dir: "models/exports"
  results_dir: "results"
  logs_dir: "logs"

# Class Names - Type Detection (Stage 1)
classes:
  - "fork"
  - "knife"
  - "spoon"

# Manufacturer Classes (for future Stage 2 models)
manufacturers:
  ikea:
    - "ikea_fork"
    - "ikea_knife"
    - "ikea_spoon"
  obh:
    - "obh_fork"
    - "obh_knife"
    - "obh_spoon"

# Evaluation
evaluation:
  metrics: ["accuracy", "precision", "recall", "f1"]
  confusion_matrix: true
  grad_cam: true
  grad_cam_samples: 10
  top_k: 3

# Export Settings
export:
  formats: ["pt", "onnx", "torchscript"]
  optimize_for_mobile: false
  quantization: false

# Logging
logging:
  level: "INFO"
  tensorboard: true
  save_plots: true
  plot_format: "png"
  plot_dpi: 300

# Hardware
device: "auto" # Options: auto, cpu, cuda
mixed_precision: false
